# Generated by Django 4.0.6 on 2022-08-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'All Images'},
        ),
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='original_image',
            field=models.FileField(default=0, upload_to='', verbose_name='Original image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='processed_image',
            field=models.FileField(default=1, upload_to='', verbose_name='Processed image'),
            preserve_default=False,
        ),
    ]
